# Generated by Django 5.1.4 on 2024-12-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='image_pred',
            field=models.ImageField(default='default_pred.jpg', upload_to='images/'),
        ),
    ]
