# Generated by Django 5.1.4 on 2024-12-25 06:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='image_pred',
            field=models.ImageField(default='default_pred.jpg', upload_to='images/pred/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
